# fly.toml app configuration file generated for tavish-board on 2024-12-27T14:21:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tavish-board'
primary_region = 'ewr'

[build]

[env]
FRONTEND_URL = 'https://tavish-board.fly.dev'
PORT = '3000'

[processes]
app = 'bun start'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
